[package]
name = "fuser_git_example_linux_kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
fuser_git = { path = "../.." }
opentelemetry = "0.23.0"
opentelemetry-semantic-conventions = "0.15.0"
opentelemetry-stdout = "0.4.0"
opentelemetry_sdk = "0.23.0"
